### ISSUE TITLE
error in seeing metrics

### ISSUE THREAD

**Issue by pochadri** [yunyu/vertx-console#1] opened 2017-09-08 18:17 UTC
i am seeing the below error in browser when trying to see the metrics

TypeError: Cannot read property 'metrics' of undefined
    at o.getSimpleMetricValue (metrics.js?892684315:1)
    at o.n [as getSimpleMetricValue] (base.js?651738121:1)
    at o.render (metrics.js?892684315:9)
    at o.t._render (base.js?651738121:1)
    at o.i (base.js?651738121:1)
    at Qi.get (base.js?651738121:1)
    at Qi.run (base.js?651738121:1)
    at St (base.js?651738121:1)
    at Array.<anonymous> (base.js?651738121:1)
    at t (base.js?651738121:1)

**Comment by yunyu** [comment] 2017-09-09 02:02
What are you seeing in /admin/metrics (or equivalent with basepath)? e.g.

```
# HELP vertx_event_loop_threads The number of Vert.x event loop threads used
# TYPE vertx_event_loop_threads gauge
vertx_event_loop_threads 8.0
# HELP jvm_info JVM version info
# TYPE jvm_info gauge
jvm_info{version="1.8.0_144-b01",vendor="Oracle Corporation",} 1.0
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 89.0
# HELP jvm_threads_daemon Daemon thread count of a JVM
# TYPE jvm_threads_daemon gauge
jvm_threads_daemon 6.0
# HELP jvm_threads_peak Peak thread count of a JVM
# TYPE jvm_threads_peak gauge
jvm_threads_peak 90.0
# HELP jvm_threads_started_total Started thread count of a JVM
# TYPE jvm_threads_started_total counter
jvm_threads_started_total 123.0
```

**Comment by pochadri** [comment] 2017-09-11 11:55
Yes I am seeing the similar response for /admin/metrics

**Comment by yunyu** [comment] 2017-09-11 11:56
Can you paste the entire output? The probable cause of this issue is Dropwizard not being registered properly.

What are your JVM flags?

**Comment by k-mooijman** [comment] 2017-09-12 09:58
i have the same issue , i can see the /admin/metrics output but it does not translate to graphs
My project is started from Intellij and i use the following flags in the VM options: 

-ea -javaagent:"./quasar-core-0.7.6-jdk8.jar"  -Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.registryName=vertx-dw  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory

**Comment by yunyu** [comment] 2017-09-12 11:50
@k-mooijman What is the full output from /admin/metrics?

**Comment by k-mooijman** [comment] 2017-09-12 11:58
<pre> 
# HELP os_load_average The system load average for the last minute
# TYPE os_load_average gauge
os_load_average 1.12
# HELP os_avail_processors The number of processors available to the Java virtual machine
# TYPE os_avail_processors gauge
os_avail_processors 8.0
# HELP os_info Operating system info
# TYPE os_info gauge
os_info{name="Linux",arch="amd64",version="4.4.87-1-MANJARO",} 1.0
# HELP os_system_cpu_load The system CPU load as a number between 0 and 1
# TYPE os_system_cpu_load gauge
os_system_cpu_load 0.1502463054187192
# HELP process_cpu_load The process CPU load as a number between 0 and 1
# TYPE process_cpu_load gauge
process_cpu_load 0.0012315270935960591
# HELP os_memory_bytes_max Max available physical memory
# TYPE os_memory_bytes_max gauge
os_memory_bytes_max 1.6648720384E10
# HELP os_memory_bytes_used Used physical memory
# TYPE os_memory_bytes_used gauge
os_memory_bytes_used 1.6142077952E10
# HELP os_swap_bytes_max Max available swap space
# TYPE os_swap_bytes_max gauge
os_swap_bytes_max 1.7825787904E10
# HELP os_swap_bytes_used Used swap space
# TYPE os_swap_bytes_used gauge
os_swap_bytes_used 2.703736832E9
# HELP disk_space_bytes_used The disk space used in bytes for the default filesystem
# TYPE disk_space_bytes_used gauge
disk_space_bytes_used 4.6533402624E11
# HELP disk_space_bytes_max The total disk space in bytes for the default filesystem
# TYPE disk_space_bytes_max gauge
disk_space_bytes_max 8.6052958208E11
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 47.17
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.505209363509E9
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 175.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 4096.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.0076790784E10
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 6.6025472E8
# HELP jvm_classes_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_loaded gauge
jvm_classes_loaded 5199.0
# HELP jvm_classes_loaded_total The total number of classes that have been loaded since the JVM has started execution
# TYPE jvm_classes_loaded_total counter
jvm_classes_loaded_total 5199.0
# HELP jvm_classes_unloaded_total The total number of classes that have been unloaded since the JVM has started execution
# TYPE jvm_classes_unloaded_total counter
jvm_classes_unloaded_total 0.0
# HELP jvm_memory_bytes_used Used bytes of a given JVM memory area.
# TYPE jvm_memory_bytes_used gauge
jvm_memory_bytes_used{area="heap",} 3.2741764E8
jvm_memory_bytes_used{area="nonheap",} 4.9946312E7
# HELP jvm_memory_bytes_committed Committed (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_committed gauge
jvm_memory_bytes_committed{area="heap",} 6.33864192E8
jvm_memory_bytes_committed{area="nonheap",} 5.2494336E7
# HELP jvm_memory_bytes_max Max (bytes) of a given JVM memory area.
# TYPE jvm_memory_bytes_max gauge
jvm_memory_bytes_max{area="heap",} 3.700424704E9
jvm_memory_bytes_max{area="nonheap",} -1.0
# HELP jvm_memory_pool_bytes_used Used bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_used gauge
jvm_memory_pool_bytes_used{pool="Code Cache",} 1.4596352E7
jvm_memory_pool_bytes_used{pool="Metaspace",} 3.174388E7
jvm_memory_pool_bytes_used{pool="Compressed Class Space",} 3606080.0
jvm_memory_pool_bytes_used{pool="PS Eden Space",} 2.96216576E8
jvm_memory_pool_bytes_used{pool="PS Survivor Space",} 1.4836424E7
jvm_memory_pool_bytes_used{pool="PS Old Gen",} 1.636464E7
# HELP jvm_memory_pool_bytes_committed Committed bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_committed gauge
jvm_memory_pool_bytes_committed{pool="Code Cache",} 1.47456E7
jvm_memory_pool_bytes_committed{pool="Metaspace",} 3.3816576E7
jvm_memory_pool_bytes_committed{pool="Compressed Class Space",} 3932160.0
jvm_memory_pool_bytes_committed{pool="PS Eden Space",} 5.17472256E8
jvm_memory_pool_bytes_committed{pool="PS Survivor Space",} 1.6777216E7
jvm_memory_pool_bytes_committed{pool="PS Old Gen",} 9.961472E7
# HELP jvm_memory_pool_bytes_max Max bytes of a given JVM memory pool.
# TYPE jvm_memory_pool_bytes_max gauge
jvm_memory_pool_bytes_max{pool="Code Cache",} 2.5165824E8
jvm_memory_pool_bytes_max{pool="Metaspace",} -1.0
jvm_memory_pool_bytes_max{pool="Compressed Class Space",} 1.073741824E9
jvm_memory_pool_bytes_max{pool="PS Eden Space",} 1.352138752E9
jvm_memory_pool_bytes_max{pool="PS Survivor Space",} 1.6777216E7
jvm_memory_pool_bytes_max{pool="PS Old Gen",} 2.775580672E9
# HELP jvm_info JVM version info
# TYPE jvm_info gauge
jvm_info{version="1.8.0_144-b01",vendor="Oracle Corporation",} 1.0
# HELP vertx_event_loop_threads The number of Vert.x event loop threads used
# TYPE vertx_event_loop_threads gauge
vertx_event_loop_threads 14.0
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 49.0
# HELP jvm_threads_daemon Daemon thread count of a JVM
# TYPE jvm_threads_daemon gauge
jvm_threads_daemon 12.0
# HELP jvm_threads_peak Peak thread count of a JVM
# TYPE jvm_threads_peak gauge
jvm_threads_peak 49.0
# HELP jvm_threads_started_total Started thread count of a JVM
# TYPE jvm_threads_started_total counter
jvm_threads_started_total 51.0
# HELP jvm_threads_deadlocked Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers
# TYPE jvm_threads_deadlocked gauge
jvm_threads_deadlocked 0.0
# HELP jvm_threads_deadlocked_monitor Cycles of JVM-threads that are in deadlock waiting to acquire object monitors
# TYPE jvm_threads_deadlocked_monitor gauge
jvm_threads_deadlocked_monitor 0.0
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="PS Scavenge",} 9.0
jvm_gc_collection_seconds_sum{gc="PS Scavenge",} 0.306
jvm_gc_collection_seconds_count{gc="PS MarkSweep",} 1.0
jvm_gc_collection_seconds_sum{gc="PS MarkSweep",} 0.044

</pre>

**Comment by yunyu** [comment] 2017-09-12 11:59
Hmm, every single one of the Vert.x web metrics seem to be missing. That's very strange, how are you initializing MetricsConsolePage?

**Comment by k-mooijman** [comment] 2017-09-12 12:02
This is in my webverticle : 

`

		MetricsService metricsService = MetricsService.create(vertx);
		HealthChecks healthChecks = HealthChecks.create(vertx);

		ServiceDiscovery discovery = ServiceDiscovery.create(vertx);
		MetricRegistry dropwizardRegistry = SharedMetricRegistries.getOrCreate( System.getProperty("vertx.metrics.options.registryName") );


		WebConsoleRegistry.create("/admin")
				// Add pages
				.addPage(MetricsConsolePage.create(dropwizardRegistry))
				.addPage(ServicesConsolePage.create(discovery))
				.addPage(LoggingConsolePage.create())
				.addPage(CircuitBreakersConsolePage.create())
				.addPage(ShellConsolePage.create())
				.addPage(HealthConsolePage.create(healthChecks))
				.addPage(HttpClientsConsolePage.create(metricsService))
				.setCacheBusterEnabled(true) // Adds random query string to scripts
				// Mount to router
				.mount(vertx, mainRouter);


		server.requestHandler(fiberHandler(mainRouter::accept)).listen(config().getInteger("port"));

`

**Comment by yunyu** [comment] 2017-09-12 12:17
I'm going to set up a test project with similar initialization code after class. There's a chance that Vert.x Dropwizard behavior changed but that's unlikely. What are the versions of your Vert.x dependencies?

**Comment by k-mooijman** [comment] 2017-09-12 13:10
I'm using vertx 3.4.2

**Comment by yunyu** [comment] 2017-09-14 20:49
Hmm, I was unable to reproduce this with basically the simplest possible hello world + metrics setup. Can you try hardcoding the registry name?

**Comment by k-mooijman** [comment] 2017-09-15 08:21
i tried  hardcoding the registry name but with no result.
I have a feeling it could be a version difference , can you confirm if the vertx.console.version is 

"b39d65ca8d"

 ?
I used it from your example on this git page.

**Comment by k-mooijman** [comment] 2017-09-15 08:37
I'm using gradle 
I'm suspecting the build.gradle i have does not  compile the correct versions 

My gradle file : 


```
plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '1.2.4'
    id 'jacoco'
    id 'idea'
}

mainClassName='nl.twensoc.setso.Application'

/*
 * TODO: Gets the version name from the latest Git tag
 * http://ryanharter.com/blog/2013/07/30/automatic-versioning-with-git-and-gradle/
 */

dependencies {
    compile "io.vertx:vertx-core:$vertxVersion"
    compile "io.vertx:vertx-codegen:$vertxVersion"
    compile "io.vertx:vertx-service-proxy:$vertxVersion"
    compile "io.vertx:vertx-web:$vertxVersion"
    compile "io.vertx:vertx-auth:$vertxVersion"
    compile "io.vertx:vertx-sync:$vertxVersion"
    compile "io.vertx:vertx-mail-client:$vertxVersion"
    compile "io.vertx:vertx-auth-common:$vertxVersion"
    compile "io.vertx:vertx-auth-jwt:$vertxVersion"
    compile "io.vertx:vertx-jdbc-client:$vertxVersion"
    compile "io.vertx:vertx-dropwizard-metrics:$vertxVersion"
    compile "io.vertx:vertx-health-check:$vertxVersion"
    compile "io.vertx:vertx-service-discovery:$vertxVersion"
    compile "io.vertx:vertx-shell:$vertxVersion"

    compile "org.freemarker:freemarker:$freemarkerVersion"
    compile "co.paralleluniverse:quasar-core:$quasarVersion"
    compile "org.postgresql:postgresql:$postgresversion"

    //compile "org.slf4j:slf4j-api:1.7.10"
    compile "ch.qos.logback:logback-classic:$logbackVersion"

    compile "nl.twensoc:twensoc-vertx-core:$twensocVertxVersion"
    compile "nl.twensoc:twensoc-vertx-dashboard:$twensocVertxVersion"
    compile "nl.twensoc:twensoc-vertx-notification:$twensocVertxVersion"
    compile "nl.twensoc:twensoc-vertx-file:$twensocVertxVersion"

    //compile "nl.twensoc.vertx:utils:$twensocVertxVersion"
    //compile "nl.twensoc.vertx:relational-db-service:$twensocVertxVersion"
    testCompile "junit:junit:$junitVersion"
    testCompile "io.vertx:vertx-unit:$vertxVersion"
    testCompile "org.subethamail:subethasmtp:3.1.7"
    testCompile "nl.twensoc:twensoc-vertx-testlib:$twensocVertxVersion"
    testCompile "io.vertx:vertx-web-client:$vertxVersion"


    compile "com.github.yunyu.vertx-console:vertx-console-base:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-services:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-metrics:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-logging:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-health:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-http-clients:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-circuit-breakers:$vertxConsoleVersion"
    compile "com.github.yunyu.vertx-console:vertx-console-shell:$vertxConsoleVersion"

    compile "io.prometheus:simpleclient_hotspot:0.0.23"
    compile "io.prometheus:simpleclient_dropwizard:0.0.23"
    compile "com.github.yunyu:prometheus-jvm-extras:1.2-SNAPSHOT"

    // Needed for cobertura tests
    // https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/usage.md
    // testRuntime "org.slf4j:slf4j-api:1.7.10"
}
repositories {
    mavenCentral()
    mavenLocal()

    maven {
        url = 'http://oss.sonatype.org/content/repositories/snapshots/'
    }
    maven{
        url = 'https://jitpack.io'
    }
}
test {
    jvmArgs	"-javaagent:./quasar-core-$quasarVersion-jdk8.jar"
    exclude '**/*TestSuite*'
    exclude '**/Measurement*'
    //include '**/**ListTest'
    // listen to events in the test execution lifecycle
    beforeTest { descriptor ->
        logger.lifecycle("Running test: " + descriptor)
    }
    testLogging.showStandardStreams = true
    testLogging.exceptionFormat = 'full'
    systemProperty "vertx.logger-delegate-factory-class-name", "io.vertx.core.logging.SLF4JLogDelegateFactory"
}

shadowJar {
    classifier = 'fat'
    manifest {
        attributes 'Main-Class': '$mainClassName'
    }
    exclude 'META-INF/LICENSE'
    exclude 'LICENSE'
    mergeServiceFiles {
        include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '3.2.1'
}




```

**Comment by k-mooijman** [comment] 2017-09-15 13:05
Ok i managed getting it to work ! 
I'm not quite sure what solved it but i think it is or the way the parameters were given to the app in the start sequence (intellij ) or way the options were given when initializing vertx

**Comment by yunyu** [comment] 2017-09-15 16:52
Good to hear. What were the new flags? They might be helpful to @pochadri

**Closed as completed by yunyu** 2017-09-15 16:52 UTC

**Comment by k-mooijman** [comment] 2017-09-16 09:10
in Intellij in the run/debug Configurations iset the following:
vm options :  -Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.registryName=vertx-dw
Program arguments :  -Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.registryName=vertx-dw ( i first had this in vm options ) 

And then i used : 
```
JsonObject vertxConfig = config.getJsonObject("vertx");
VertxOptions vertxOptions = new VertxOptions(vertxConfig);
vertxOptions.setMetricsOptions(new DropwizardMetricsOptions().setEnabled(true).setRegistryName("vertx-dw"));
vertx = Vertx.vertx(vertxOptions);
```
to startup the Dropwizard 

And in the webverticle : 
```
MetricRegistry dropwizardRegistry = SharedMetricRegistries.getOrCreate( "vertx-dw");

```

**Comment by dvysotskiy** [comment] 2019-01-28 21:31
You can reproduce the issue by specifying `-Dvertx.metrics.options.enabled=true` but not the `-Dvertx.metrics.options.registryName=...`.
